import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => (
    <>
      <Head>
        <title>Old Lang Signs</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* a navbar that is light when in light mode. Fixed to the top */}
        <nav className="bg-white dark:bg-gray-800 shadow-md fixed w-full z-10 top-0">
          {/* links to About Gallery and Contact pages */}
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex items-center justify-between h-16">
              <div className="flex items-center">
                <div className="flex-shrink-0">
                  <h3 className="text-2xl font-bold text-gray-900 dark:text-gray-100">Old Lang Signs</h3>
                </div>
                <div className="hidden md:block">
                  <div className="ml-10 flex items-baseline space-x-4">
                    <Link href='/about' className="text-gray-900 dark:text-gray-100 hover:bg-gray-300 dark:hover:bg-gray-700 px-3 py-2 rounded-md text-sm font-medium">
                      About
                    </Link>
                    <Link href="/gallery" className="text-gray-900 dark:text-gray-100 hover:bg-gray-300 dark:hover:bg-gray-700 px-3 py-2 rounded-md text-sm font-medium">
                      Gallery
                    </Link>
                    <Link href="/contact" className="text-gray-900 dark:text-gray-100 hover:bg-gray-300 dark:hover:bg-gray-700 px-3 py-2 rounded-md text-sm font-medium">
                      Contact
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </nav>
        {/* fullscreen div that is light but dark in dark mode. Has 2 columns with the right filled with lorem ipsum filler text */}
        <div 
          className="bg-white dark:bg-gray-800 h-screen flex flex-col justify-center items-center"
        >
          <p className="text-4xl font-bold text-gray-900 dark:text-gray-100">Under Construction...</p>
        </div>
      </main>
    </>
  );

export default Home;